routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth','prefix' => 'roulette'],function () {
    Route::get('/', 'RouletteController@index');
    Route::post('/update', 'RouletteController@update');
});
Route::group(['middleware' => 'auth','prefix' => 'admin-list'],function () {
    Route::get('/', 'UserController@index');
});
Route::group(['middleware' => 'auth','prefix' => 'create-admin'],function () {
    Route::get('/', 'UserController@create');
    Route::post('/', 'UserController@store');
});
Route::group(['middleware' => 'auth','prefix' => 'users'],function () {
    Route::get('/', 'UserController@index');
    Route::post('/', 'UserController@update');
});

Route::group(['middleware' => 'auth','prefix' => 'bet'],function () {
    Route::get('/', 'HomeController@bet');
    Route::post('/', 'HomeController@place_bet');
});

app/Bet.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Bet extends Model
{
    //
}

app/Roulette.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Roulette extends Model
{
    protected $guarded = [];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name','last_name','mobile_number','gender','birthdate','email', 'password', 'balance','bet','role',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function getFullNameAttribute()
    {
        return "{$this->first_name} {$this->last_name}";
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use App\Roulette;
use Auth;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $users = User::where('role','!=',1)->paginate(5);
        return view('home',compact('users'));
    }

    public function bet()
    {
        $roulettes = Roulette::all();
        return view('user.bet',compact('roulettes'));
    }

    public function place_bet(Request $request)
    {   
        if($request->amount >= 1) {
            if(Auth::user()->balance >= $request->amount) {
                $user = Auth::user();
                $user->balance = $user->balance - $request->amount;
                $user->bet = $user->bet + $request->amount;
                $user->save();
                return redirect()->back()->with('bet_success-'.$request->roulette_id, 'Bet successfully placed'); 
            }else{
                return redirect()->back()->with('bet_error-'.$request->roulette_id, 'Insufficient funds'); 
            }
        }else{
            return redirect()->back()->with('bet_error-'.$request->roulette_id, 'Invalid amount'); 
        }
    }
}

app/Http/Controllers/RouletteController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Roulette;
use DB;

class RouletteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $roulettes = Roulette::all();
        return view('admin.roulette',compact('roulettes'));
    }

    public function update(Request $request)
    {
        DB::beginTransaction();
        try {
            $to_update = [];
            foreach($request->except('_token') as $key=>$value) {
                $key = explode('-',$key);
                $to_update[$key[1]][$key[0]] = $value;   
            }
            foreach($to_update as $id => $data) {
                Roulette::find($id)->update($data);
            }
            DB::commit();
            return redirect()->back()->with('success', 'Roulettes successfully updated');   
        } catch (\Throwable $th) {
            DB::rollback();
            return redirect()->back()->with('error', 'Something went wrong');   
        }
       
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    public function index()
    {
        $users = User::where('role','=',1)->paginate(5);
        return view('admin.admin-list',compact('users'));
    }

    public function update(Request $request) {
        foreach($request->except('_token') as $key=>$value) {
            $key = explode('-',$key);
            if($key[0] == 'button') {
                User::find($key[1])->update([
                    'balance' => $request['amount-'.$key[1]],
                    'bet' => $request['bet-'.$key[1]]
                ]);
                return redirect()->back()->with('success', 'User successfully updated');   
            }   
        }

    }

    public function create() {
        return view('admin.add-admin');
    }

    public function store(Request $request) {
        $validator = Validator::make($request->all(), [
            'first_name' => ['required', 'string', 'max:255'],
            'last_name' => ['required', 'string', 'max:255'],
            'gender' => ['required', 'string', 'max:255'],
            'birthdate' => ['required', 'string', 'max:255'],
            'mobile_number' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
            'password' => ['required', 'string', 'min:8', 'confirmed'],
        ]);

        if ($validator->fails()) {
            return redirect('/create-admin')
                        ->withErrors($validator)
                        ->withInput();
        }

        User::create([
            'first_name' => $request->first_name,
            'last_name' => $request->last_name,
            'gender' => $request->gender,
            'birthdate' => $request->birthdate,
            'mobile_number' => $request->mobile_number,
            'role' => 1,
            'email' => $request->email,
            'password' => Hash::make($request->password),
        ]);

        return redirect('/admin-list')->with('success', 'Admin successfully created');   
    }
}

resources/views/admin/add-admin.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Add Admin</div>

                <div class="card-body">
                    <form method="POST" action="/create-admin">
                        @csrf

                        <div class="form-group row">
                            <label for="first_name" class="col-md-4 col-form-label text-md-right">First Name</label>

                            <div class="col-md-6">
                                <input id="first_name" type="text" class="form-control @error('first_name') is-invalid @enderror" name="first_name" value="{{ old('first_name') }}" required autocomplete="first_name" autofocus>

                                @error('first_name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="last_name" class="col-md-4 col-form-label text-md-right">Last Name</label>

                            <div class="col-md-6">
                                <input id="last_name" type="text" class="form-control @error('last_name') is-invalid @enderror" name="last_name" value="{{ old('last_name') }}" required autocomplete="last_name" autofocus>

                                @error('last_name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required autocomplete="email">

                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">Mobile Number</label>

                            <div class="col-md-6">
                                <input id="email" type="text" class="form-control @error('mobile_number') is-invalid @enderror" name="mobile_number" value="{{ old('mobile_number') }}" required autocomplete="mobile_number">

                                @error('mobile_number')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="gender" class="col-md-4 col-form-label text-md-right">Gender</label>

                            <div class="col-md-6">
                                <select id="gender" class="form-control @error('gender') is-invalid @enderror" name="gender" value="{{ old('gender') }}" required>
                                    <option value="male">Male</option>
                                    <option value="female">Female</option>
                                </select>

                                @error('gender')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="birthdate" class="col-md-4 col-form-label text-md-right">Birthday</label>
                            <div class="col-md-6">
                                <input id="birthdate" type="text" class="form-control @error('birthdate') is-invalid @enderror" name="birthdate" value="{{ old('birthdate') }}" >
                                @error('birthdate')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" required autocomplete="new-password">

                                @error('password')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password-confirm" class="col-md-4 col-form-label text-md-right">{{ __('Confirm Password') }}</label>

                            <div class="col-md-6">
                                <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required autocomplete="new-password">
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Register') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/admin-list.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    @if (\Session::has('success'))
                        <div class="alert alert-success">
                            <ul>
                                <li>{!! \Session::get('success') !!}</li>
                            </ul>
                        </div>
                    @endif

                    <div class="container" style="overflow-x : auto">
                        <h3>Registered Admins <a class="btn btn-primary btn-sm" href="/create-admin"> Add Admin</a></h3>
                        <form method="POST" action="/users">
                            @csrf
                            <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <td>Name</td>
                                        <td>Mobile Number</td>
                                        <td>Birthday</td>
                                        <td>Gender</td>
                                        <td>Email</td>
                                        <td>Created at</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($users as $user)
                                        <tr>
                                                <td>
                                                    {{ $user->full_name }}
                                                </td>
                                                <td>{{ $user->mobile_number }}</td>
                                                <td>{{ $user->birthdate }}</td>
                                                <td>{{ $user->gender }}</td>
                                                <td>{{ $user->email }}</td>
                                                <td>{{ $user->created_at }}</td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </form>
                        {{ $users->links() }}
                </div>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/roulette.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Roulette Maintenance</div> 
                <div class="card-body">
                    @if (\Session::has('success'))
                        <div class="alert alert-success">
                            <ul>
                                <li>{!! \Session::get('success') !!}</li>
                            </ul>
                        </div>
                    @endif
                    <form method="POST" action="/roulette/update">
                        @csrf

                        <div class="row justify-content-center">
                            @foreach($roulettes as $roulette)
                            <div class="col-md-5" style="margin-bottom : 10px;">
                                <div class="card">
                                    <div class="card-header"><input type="text" class="form-control" name="name-{{ $roulette->id }}" value="{{ $roulette->name }}"></div> 
                                    <div class="card-body">
                                        <input type="text" class="form-control" name="title-{{ $roulette->id }}" value="{{ $roulette->title }}">
                                    </div>
                                </div>
                            </div>
                            @endforeach
                        </div> 
                        <br>
                        <button type="submit" class="btn btn-primary">Save</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    @if (\Session::has('success'))
                        <div class="alert alert-success">
                            <ul>
                                <li>{!! \Session::get('success') !!}</li>
                            </ul>
                        </div>
                    @endif

                    <div class="container" style="overflow-x : auto">
                    @if(Auth::user()->role == 1)
                        <h3>Registerd Users</h3>
                        <form method="POST" action="/user">
                            @csrf
                            <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <td>Name</td>
                                        <td>Mobile Number</td>
                                        <td>Birthday</td>
                                        <td>Gender</td>
                                        <td>Email</td>
                                        <td>Bet</td>
                                        <td>Balance</td>
                                        <td>Created at</td>
                                        <td>Action</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($users as $user)
                                        <tr>
                                        
                                                <td>
                                                    {{ $user->full_name }}
                                                </td>
                                                <td>{{ $user->mobile_number }}</td>
                                                <td>{{ $user->birthdate }}</td>
                                                <td>{{ $user->gender }}</td>
                                                <td>{{ $user->email }}</td>
                                                <td>
                                                    <input type="text" name="bet-{{$user->id}}" value="{{ $user->bet }}">
                                                </td>
                                                <td>
                                                    <input type="text" name="amount-{{$user->id}}" value="{{ $user->balance }}">
                                                </td>
                                                <td>{{ $user->created_at }}</td>
                                                <td>
                                                    <button type="submit" name="button-{{$user->id}}" class="btn btn-primary btn-sm">Update</button>
                                                </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </form>
                        {{ $users->links() }}
                    @else
                        <p>Name : {{ Auth::user()->full_name }}</p>
                        <p>Mobile Number : {{ Auth::user()->mobile_number }}</p>
                        <p>Birthday : {{ Auth::user()->birthdate }}</p>
                        <p>Gender : {{ Auth::user()->gender }}</p>
                        <p>Email : {{ Auth::user()->email }}</p>
                        <p>Balance : {{ Auth::user()->balance }}</p>
                        <p>Created at : {{ Auth::user()->created_at }}</p>
                        <a href="/bet" class="btn btn-primary">Start to bet</a>
                    @endif
                </div>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->full_name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>
                                    @if(Auth::user()->role == 1)
                                        <a class="dropdown-item" href="/roulette">
                                            Roulette Maintenance
                                        </a>
                                        <a class="dropdown-item" href="/home">
                                            Users
                                        </a>
                                        <a class="dropdown-item" href="/admin-list">
                                            Admins
                                        </a>
                                    @endif
                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/user/bet.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Bet on roulette</div> 
                <div class="card-body">
                    @if (\Session::has('success'))
                        <div class="alert alert-success">
                            <ul>
                                <li>{!! \Session::get('success') !!}</li>
                            </ul>
                        </div>
                    @endif
                        <div class="row justify-content-center">
                            @foreach($roulettes as $roulette)
                                <div class="col-md-5" style="margin-bottom : 10px;">
                                    @if (\Session::has('bet_success-'.$roulette->id))
                                        <div class="alert alert-success">
                                            <ul>
                                                <li>{!! \Session::get('bet_success-'.$roulette->id) !!}</li>
                                            </ul>
                                        </div>
                                    @endif 
                                    @if (\Session::has('bet_error-'.$roulette->id))
                                        <div class="alert alert-danger">
                                            <ul>
                                                <li>{!! \Session::get('bet_error-'.$roulette->id) !!}</li>
                                            </ul>
                                        </div>
                                    @endif 
                                    <div class="card">
                                        <div class="card-header">{{ $roulette->name }}</div> 
                                        <div class="card-body">
                                            {{ $roulette->title }}
                                        </div>
                                    </div>
                                    <br>
                                    <form method="POST" action="/bet">
                                        @csrf
                                        <input type="hidden" name="roulette_id" value="{{ $roulette->id }}">
                                        <input type="text" class="form-control" name="amount" value="0">
                                        <br>
                                        <button type="submit" class="btn btn-primary">Bet</button>
                                    </form>
                                </div>
                                <br>
                                <br>
                            @endforeach
                        </div> 
                </div>
            </div>
        </div>
    </div>
</div>
@endsection